### PR TITLE
Desafio Full Stack - Mateus Bays

### PR DESCRIPTION
**Pull request by mateusbays**
Estou entregando o teste para full stack.
No teste foi desenvolvido um serviço de autenticação, um serviço core  com as rotas de sensores, pontos de monitoramento e máquinas, ambos com Nest, e o front-end da aplicação em Next. 
Adicionei uma camada de proxy com o nginx, para não expor a rota das apis, entretanto, isso me limitou a utilizar uma máquina para fazer o deploy.
Estou tentando realizar o deploy pelo docker-compose, mas estou enfrentando alguns problemas, um deles é a parte de instalação dos pacotes, que demora muito e outra quando os serviços sobem, estou tendo alguns problemas com o Nx.

### CODE REVIEW

**Comment by mateusbays** [comment]
Aumentei a máquina para 2 cores e 2gb de ram e consegui realizar o deploy, em breve mando a url.

**Comment by mateusbays** [comment]
Pode usar essa URL que é o caminho da máquina na digital ocean que ta rodando, http://159.223.141.159:4200/auth/sign-in

**Comment by calil-amaral-dynamox** [comment]
1 - Authentication

1. [x] As a user, I want to log in using a fixed email and password so that I can access private routes.
1. [x] As a user, I want to be able to log out of the system so that I can prevent unauthorized access to my account.
1. [x] No private routes should be accessible without authentication.

2 - Machine Management

1. [x] As a user, I want to create a new machine with an arbitrary name and with a type selected from a list ["Pump", "Fan"] so that I can manage it later.
1. [ ] As a user, I want to change the attributes (name and type) of a machine after creating it so that I can keep the machine information updated.
1. [ ] As a user, I want to delete a machine when it is no longer in use so that it doesn't clutter the system.

3 - Monitoring Points and Sensors Management

1. [x] As a user, I want to create at least two monitoring points with arbitrary names for an existing machine, so that I can monitor the machine's performance.
1. [x] As a user, I want to associate a sensor to an existing monitoring point so that I can monitor the machine's performance. The sensor should have a unique ID, and the sensor model name should be one of ["TcAg", "TcAs", "HF+"].
1. [x] As a user, I want the system to prevent me from setting up "TcAg" and "TcAs" sensors for machines of the type "Pump".
1. [x] As a user, I want to see all my monitoring points in a paginated list so that I can manage them. The list should display up to 5 monitoring points per page and should include the following information: "Machine Name", "Machine Type", "Monitoring Point Name", and "Sensor Model".

> It was not possible to create more monitoring points to verify that the list is paginated with maximum 5 elements because of the previous assumption that limits to a single sensor per sensor model. :-1:

1. [x] As a user, I want to sort the monitoring points list by any of its columns in ascending or descending order, so that I can easily find the information I'm looking for.

4 - Ambiguity Handling

1. [x] Make reasonable assumptions and design the application accordingly for any ambiguities in the challenge.

> There was a confusion between "sensor model" (TcAg, TcAs, HF+) and "sensor" (single sensor of a given model), which limited the usage of the application to a single monitored point per sensor model. :-1:

1. [x] Document your assumptions in the README file.

5 - Technical requirements

1. [x] Use TypeScript.
1. [x] Use React.
1. [x] Use Redux for managing global states.
1. [ ] Use Redux Thunks or Redux Saga for managing asynchronous side effects.
1. [x] Use Next.js or Vite.
1. [x] Use Material UI 5 for styling the application.
1. [x] Create reusable components.
1. [x] The code is well-organized and documented.
1. [x] The application layout is responsive.
The choice of remaining tools is at your discretion.

6 - Bonus

1. [ ] Implement unit tests for the application (let us know how to run them, otherwise we won't be able to evaluate).

> Only generated tests were found but they do not test any valid use case.

1. [x] Implement your own back-end code. If you pick this option, write it using NodeJS JavaScript runtime (not Java, not PHP...). Although we also work with Python here, we are looking for JavaScript related skills in this test.
1. [x] If you choose to implement your own back-end, we encourage you to use either PostgreSQL or MongoDB as a persistence layer.
1. [x] If you choose to use PostgreSQL, use Prisma ORM (or even try Drizzle, or Kysely) to interact with PostgreSQL.
1. [ ] If you choose to use MongoDB, use Mongoose ORM to interact with the database;
1. [x] Use Nest.js Framework for the back-end (we are moving some services to that tool).
1. [x] Use Nx to manage the whole application as a monorepo (we use that tool a lot here).
1. [ ] Add e2e tests with Cypress (use it to test a full user flow).
1. [ ] If you were provided with a baseline code, identify any areas of bad code or suboptimal implementations and refactor them.
1. [x] Deploy your application to a cloud provider and provide a link for the running app.

> Configured the application to run within a dockerized environment. :+1:
> It was not possible to quickly reproduce the dockerized environment locally after following the README.md. :-1:

image

**Comment by calil-amaral-dynamox** [comment]
@mateusbays Thanks for your PR submission! Your implementation was evaluated and will be closed now. Wait for a contact by e-mail from our team.

**Pull request closed without merging**
