### PR TITLE
Desafio Full Stack finalizado: Projeto pronto para revisão.

### PR DESCRIPTION
**Pull request by DevP-Pro**
Ao longo do desenvolvimento, implementei as principais funcionalidades exigidas, mantendo foco tanto na performance quanto na usabilidade da aplicação.

As principais features incluem:

Autenticação segura com JWT, garantindo acesso restrito e proteção de dados sensíveis.
Gerenciamento de máquinas e sensores, permitindo a criação, edição e exclusão de registros, tudo de forma intuitiva.
Paginação e ordenação de dados nas tabelas, proporcionando uma experiência fluida mesmo com grandes volumes de dados.
Implementação de Redux para o gerenciamento de estado global, garantindo consistência entre componentes e facilitando a escalabilidade da aplicação.
Design responsivo e utilização de Material UI para garantir uma interface moderna, agradável e eficiente para o usuário final.
Além disso, priorizei a clareza no código e a estruturação das funcionalidades, pensando sempre em facilitar manutenções futuras.

Fico à disposição para qualquer ajuste necessário e estou ansioso por qualquer feedback da equipe de avaliadores.

### CODE REVIEW

**Comment by amaralc** [comment]
[EVALUATION IN PROGRESS]

1 - Authentication

1. [ ] As a user, I want to log in using a fixed email and password so that I can access private routes.
1. [ ] As a user, I want to be able to log out of the system so that I can prevent unauthorized access to my account.
1. [ ] No private routes should be accessible without authentication.

2 - Machine Management

1. [ ] As a user, I want to create a new machine with an arbitrary name and with a type selected from a list ["Pump", "Fan"] so that I can manage it later.
1. [ ] As a user, I want to change the attributes (name and type) of a machine after creating it so that I can keep the machine information updated.
1. [ ] As a user, I want to delete a machine when it is no longer in use so that it doesn't clutter the system.

3 - Monitoring Points and Sensors Management

1. [ ] As a user, I want to create at least two monitoring points with arbitrary names for an existing machine, so that I can monitor the machine's performance.
1. [ ] As a user, I want to associate a sensor to an existing monitoring point so that I can monitor the machine's performance. The sensor should have a unique ID, and the sensor model name should be one of ["TcAg", "TcAs", "HF+"].
1. [ ] As a user, I want the system to prevent me from setting up "TcAg" and "TcAs" sensors for machines of the type "Pump".
1. [ ] As a user, I want to see all my monitoring points in a paginated list so that I can manage them. The list should display up to 5 monitoring points per page and should include the following information: "Machine Name", "Machine Type", "Monitoring Point Name", and "Sensor Model".
1. [ ] As a user, I want to sort the monitoring points list by any of its columns in ascending or descending order, so that I can easily find the information I'm looking for.

4 - Ambiguity Handling

1. [ ] Make reasonable assumptions and design the application accordingly for any ambiguities in the challenge.
1. [ ] Document your assumptions in the README file.

5 - Technical requirements

1. [ ] Use TypeScript.
1. [ ] Use React.
1. [ ] Use Redux for managing global states.
1. [ ] Use Redux Thunks or Redux Saga for managing asynchronous side effects.
1. [ ] Use Next.js or Vite.
1. [ ] Use Material UI 5 for styling the application.
1. [ ] Create reusable components.
1. [ ] The code is well-organized and documented.
1. [ ] The application layout is responsive.
The choice of remaining tools is at your discretion.

6 - Bonus

1. [ ] Implement unit tests for the application (let us know how to run them, otherwise we won't be able to evaluate).
1. [ ] Implement your own back-end code. If you pick this option, write it using NodeJS JavaScript runtime (not Java, not PHP...). Although we also work with Python here, we are looking for JavaScript related skills in this test.
1. [ ] If you choose to implement your own back-end, we encourage you to use either PostgreSQL or MongoDB as a persistence layer.
1. [ ] If you choose to use PostgreSQL, use Prisma ORM (or even try Drizzle, or Kysely) to interact with PostgreSQL.
1. [ ] If you choose to use MongoDB, use Mongoose ORM to interact with the database;
1. [ ] Use Nest.js Framework for the back-end (we are moving some services to that tool).
1. [ ] Use Nx to manage the whole application as a monorepo (we use that tool a lot here).
1. [ ] Add e2e tests with Cypress (use it to test a full user flow).
1. [ ] If you were provided with a baseline code, identify any areas of bad code or suboptimal implementations and refactor them.
1. [ ] Deploy your application to a cloud provider and provide a link for the running app.

7 - Tips

1. [ ] There is no need to reinvent the wheel. You can use a Material UI 5 free template like [Devias Kit](https://mui.com/store/items/devias-kit/) to speed up the development process.
1. [ ] Not familiar with Redux? Check out [this tutorial](https://egghead.io/courses/modern-redux-with-redux-toolkit-rtk-and-typescript-64f243c8) to get started.
1. [ ] Not familiar with Cypress? Check out [these tutorials](https://learn.cypress.io/) to get started.
1. [ ] You can mock your back-end using a package like [json-server](https://www.npmjs.com/package/json-server), which creates a fake REST API. Bear in mind that those implementing their own back-end will check more boxes in the evaluation process.

</br>


## Evaluation Criteria

The items listed above will have different weights in the evaluation process. Each one of them will be evaluated as "Not Implemented", "Implemented with Issues", "Implemented", or "Implemented with Excellence". Use your judgement to prioritize the requirements you will implement in the time you have available. 

In general we will be looking for the following:

1. [ ] Anyone should be able to follow the instructions and run the application.
1. [ ] User stories were implemented according to the functional requirements.
1. [ ] Front-end code is successfully integrated with a back-end API (either a fake one, or one you built yourself).
1. [ ] Ability to refactor existing code (if applicable) and write unit tests for the written code.
1. [ ] Adherence to best practices in front-end development.
1. [ ] Problem-solving skills and ability to handle ambiguity.
1. [ ] Code quality, readability, and maintainability.

## Ready to Begin the Challenges?

1. [ ] Fork this repository to your own Github account.
1. [ ] Create a new branch using your first name and last name. For example: `caroline-oliveira`.
1. [ ] After completing the challenge, create a pull request to this repository (https://github.com/dynamox-s-a/js-ts-full-stack-test), aimed at the main branch.
1. [ ] We will receive a notification about your pull request, review your solution, and get in touch with you.

**Comment by calil-amaral-dynamox** [comment]
1 - Authentication

1. [x] As a user, I want to log in using a fixed email and password so that I can access private routes.

> Added a registration workflow that was not required but worked fine. :+1:

1. [x] As a user, I want to be able to log out of the system so that I can prevent unauthorized access to my account.
1. [x] No private routes should be accessible without authentication.

2 - Machine Management

1. [x] As a user, I want to create a new machine with an arbitrary name and with a type selected from a list ["Pump", "Fan"] so that I can manage it later.

> Added an extra field to inform if the machine is active, inactive or in maintenance. :+1:

1. [x] As a user, I want to change the attributes (name and type) of a machine after creating it so that I can keep the machine information updated.
1. [x] As a user, I want to delete a machine when it is no longer in use so that it doesn't clutter the system.

> Included message in the response to inform that all related data was also removed. :+1:

3 - Monitoring Points and Sensors Management

1. [x] As a user, I want to create at least two monitoring points with arbitrary names for an existing machine, so that I can monitor the machine's performance.
1. [x] As a user, I want to associate a sensor to an existing monitoring point so that I can monitor the machine's performance. The sensor should have a unique ID, and the sensor model name should be one of ["TcAg", "TcAs", "HF+"].
1. [x] As a user, I want the system to prevent me from setting up "TcAg" and "TcAs" sensors for machines of the type "Pump".

> The restriction of sensor type was created at the monitoring point step instead of sensor step, but it was a valid assumption. :+1: :-1: 

1. [ ] As a user, I want to see all my monitoring points in a paginated list so that I can manage them. The list should display up to 5 monitoring points per page and should include the following information: "Machine Name", "Machine Type", "Monitoring Point Name", and "Sensor Model".

> I didn't find a list with all monitoring points. :-1:
> I could find monitoring points for each machine by navigating through the "eye" icon which wasn't very intuitive. :+1: :-1:
> I was able to navigate back using breadcrumbs. :+1:

1. [x] As a user, I want to sort the monitoring points list by any of its columns in ascending or descending order, so that I can easily find the information I'm looking for.

4 - Ambiguity Handling

1. [x] Make reasonable assumptions and design the application accordingly for any ambiguities in the challenge.
1. [x] Document your assumptions in the README file.

> I found a well structured explanation with an overview of how the application works. :+1:
> There was no docker-compose.yml or any instruction of how to setup my mongo server so I needed to do it by myself. :-1:
> Setup instructions were not clear. Environment variable VITE_API_URL is not mentioned at all and without close attention, the whole test could have been done using the deployed version inadvertently. :-1:

5 - Technical requirements

1. [x] Use TypeScript.
1. [x] Use React.
1. [ ] Use Redux for managing global states.

> Redux is configured but not used. States are managed locally with useState. :-1:

1. [ ] Use Redux Thunks or Redux Saga for managing asynchronous side effects.

> Libs were installed but not used. :-1:

1. [x] Use Next.js or Vite.
1. [x] Use Material UI 5 for styling the application.
1. [x] Create reusable components.

> Basic usage of components.

1. [x] The code is well-organized and documented.

> More than one component defined in single files. :-1:
> Styles could have been separated from the rest of the component.
> Added a few comments to make it clear some assumptions. :+1:

1. [x] The application layout is responsive.

6 - Bonus

1. [ ] Implement unit tests for the application (let us know how to run them, otherwise we won't be able to evaluate).
1. [x] Implement your own back-end code. If you pick this option, write it using NodeJS JavaScript runtime (not Java, not PHP...). Although we also work with Python here, we are looking for JavaScript related skills in this test.
1. [x] If you choose to implement your own back-end, we encourage you to use either PostgreSQL or MongoDB as a persistence layer.
1. [x] If you choose to use PostgreSQL, use Prisma ORM (or even try Drizzle, or Kysely) to interact with PostgreSQL.
1. [x] If you choose to use MongoDB, use Mongoose ORM to interact with the database;
1. [ ] Use Nest.js Framework for the back-end (we are moving some services to that tool).

> NestJS was improperly used. Instead of using NestJS features, the express http adapter under the hood was the one actually used. :-1:

1. [x] Use Nx to manage the whole application as a monorepo (we use that tool a lot here).
1. [ ] Add e2e tests with Cypress (use it to test a full user flow).
1. [ ] If you were provided with a baseline code, identify any areas of bad code or suboptimal implementations and refactor them.
1. [x] Deploy your application to a cloud provider and provide a link for the running app.

</br>

## Evaluation Criteria

The items listed above will have different weights in the evaluation process. Each one of them will be evaluated as "Not Implemented", "Implemented with Issues", "Implemented", or "Implemented with Excellence". Use your judgement to prioritize the requirements you will implement in the time you have available. 

In general we will be looking for the following:

1. [ ] Anyone should be able to follow the instructions and run the application.

> Setup instructions could have been more clear. A docker-compose.yml or instructions about how to run the chosen database would help other fellow developers to evaluate your work.

1. [ ] User stories were implemented according to the functional requirements.

> One functional requirement was not implemented (listing all monitoring points).

1. [x] Front-end code is successfully integrated with a back-end API (either a fake one, or one you built yourself).
1. [ ] Ability to refactor existing code (if applicable) and write unit tests for the written code.
1. [ ] Adherence to best practices in front-end development.
1. [x] Problem-solving skills and ability to handle ambiguity.
1. [ ] Code quality, readability, and maintainability.

## Ready to Begin the Challenges?

1. [x] Fork this repository to your own Github account.
1. [ ] Create a new branch using your first name and last name. For example: `caroline-oliveira`.

> Basic instruction not followed. :-1:

1. [x] After completing the challenge, create a pull request to this repository (https://github.com/dynamox-s-a/js-ts-full-stack-test), aimed at the main branch.
1. [ ] We will receive a notification about your pull request, review your solution, and get in touch with you.

**Comment by calil-amaral-dynamox** [comment]
@DevP-Pro Thanks for your PR submission! Your implementation was evaluated and will be closed now. Wait for a contact by e-mail from our team.

**Comment by adrianodev97** [comment]
1 - Authentication

- [x] As a user, I want to log in using a fixed email and password so that I can access private routes.
  > Added sign up to register new users
- [x] As a user, I want to be able to log out of the system so that I can prevent unauthorized access to my account.
- [x] No private routes should be accessible without authentication.

2 - Machine Management

- [x] As a user, I want to create a new machine with an arbitrary name and with a type selected from a list ["Pump", "Fan"] so that I can manage it later.
- [x] As a user, I want to change the attributes (name and type) of a machine after creating it so that I can keep the machine information updated.
- [x] As a user, I want to delete a machine when it is no longer in use so that it doesn't clutter the system.

3 - Monitoring Points and Sensors Management

- [x] As a user, I want to create at least two monitoring points with arbitrary names for an existing machine, so that I can monitor the machine's performance.
- [x] As a user, I want to associate a sensor to an existing monitoring point so that I can monitor the machine's performance. The sensor should have a unique ID, and the sensor model name should be one of ["TcAg", "TcAs", "HF+"].
- [x] As a user, I want the system to prevent me from setting up "TcAg" and "TcAs" sensors for machines of the type "Pump".
- [ ] ~~As a user, I want to see all my monitoring points in a paginated list so that I can manage them. The list should display up to 5 monitoring points per page and should include the following information: "Machine Name", "Machine Type", "Monitoring Point Name", and "Sensor Model".~~
- [x] As a user, I want to sort the monitoring points list by any of its columns in ascending or descending order, so that I can easily find the information I'm looking for.

4 - Ambiguity Handling

- [x] Make reasonable assumptions and design the application accordingly for any ambiguities in the challenge.
- [x] Document your assumptions in the README file.

5 - Technical requirements

- [x] Use TypeScript.
- [x] Use React.
- [ ] ~~Use Redux for managing global states.~~
  > Was implemented, but not used
- [ ] ~~Use Redux Thunks or Redux Saga for managing asynchronous side effects.~~
  > Was implemented, but not used
- [x] Use Next.js or Vite.
  > Used vite
- [x] Use Material UI 5 for styling the application.
- [x] Create reusable components.
- [x] The code is well-organized and documented.
  > Could be improved
  > Lots of unnecessary comments
  > Lots of code unused
- [x] The application layout is responsive. The choice of remaining tools is at your discretion.
  > Some components can be improved about responsivity

6 - Bonus

- [ ] Implement unit tests for the application (let us know how to run them, otherwise we won't be able to evaluate).
- [x] Implement your own back-end code. If you pick this option, write it using NodeJS JavaScript runtime (not Java, not PHP...). Although we also work with Python here, we are looking for JavaScript related skills in this test.
- [x] If you choose to implement your own back-end, we encourage you to use either PostgreSQL or MongoDB as a persistence layer.
  > Mongo
- [x] If you choose to use PostgreSQL, use Prisma ORM (or even try Drizzle, or Kysely) to interact with PostgreSQL.
- [x] If you choose to use MongoDB, use Mongoose ORM to interact with the database;
- [ ] Use Nest.js Framework for the back-end (we are moving some services to that tool).
- [x] Use Nx to manage the whole application as a monorepo (we use that tool a lot here).
- [ ] Add e2e tests with Cypress (use it to test a full user flow).
- [ ] If you were provided with a baseline code, identify any areas of bad code or suboptimal implementations and refactor them.
- [x] Deploy your application to a cloud provider and provide a link for the running app.
  > Heroku

**Evaluation Criteria**

- [ ] Anyone should be able to follow the instructions and run the application.
  > Could be add steps to run the database
- [ ] User stories were implemented according to the functional requirements.
- [x] Front-end code is successfully integrated with a back-end API (either a fake one, or one you built yourself).
- [ ] Ability to refactor existing code (if applicable) and write unit tests for the written code.
- [ ] Adherence to best practices in front-end development.
- [x] Problem-solving skills and ability to handle ambiguity.
- [ ] Code quality, readability, and maintainability.

## Ready to Begin the Challenges?

- [x] Fork this repository to your own Github account.
  > The purpose of the 'fork' is to track the time the developer takes to complete the project, documenting the process through commits, which will serve as proof of their knowledge in Git
- [ ] Create a new branch using your first name and last name. For example: `caroline-oliveira`.
- [x] After completing the challenge, create a pull request to this repository (https://github.com/dynamox-s-a/js-ts-full-stack-test), aimed at the main branch.
  > Test was implemented in another repository and after done, the code was moved to the fork and pushed in only one commit

**Comment by adriano-junior-dynamox** [comment]
1 - Authentication

- [x] As a user, I want to log in using a fixed email and password so that I can access private routes.
  > Added sign up to register new users
- [x] As a user, I want to be able to log out of the system so that I can prevent unauthorized access to my account.
- [x] No private routes should be accessible without authentication.

2 - Machine Management

- [x] As a user, I want to create a new machine with an arbitrary name and with a type selected from a list ["Pump", "Fan"] so that I can manage it later.
- [x] As a user, I want to change the attributes (name and type) of a machine after creating it so that I can keep the machine information updated.
- [x] As a user, I want to delete a machine when it is no longer in use so that it doesn't clutter the system.

3 - Monitoring Points and Sensors Management

- [x] As a user, I want to create at least two monitoring points with arbitrary names for an existing machine, so that I can monitor the machine's performance.
- [x] As a user, I want to associate a sensor to an existing monitoring point so that I can monitor the machine's performance. The sensor should have a unique ID, and the sensor model name should be one of ["TcAg", "TcAs", "HF+"].
- [x] As a user, I want the system to prevent me from setting up "TcAg" and "TcAs" sensors for machines of the type "Pump".
- [ ] ~~As a user, I want to see all my monitoring points in a paginated list so that I can manage them. The list should display up to 5 monitoring points per page and should include the following information: "Machine Name", "Machine Type", "Monitoring Point Name", and "Sensor Model".~~
- [x] As a user, I want to sort the monitoring points list by any of its columns in ascending or descending order, so that I can easily find the information I'm looking for.

4 - Ambiguity Handling

- [x] Make reasonable assumptions and design the application accordingly for any ambiguities in the challenge.
- [x] Document your assumptions in the README file.

5 - Technical requirements

- [x] Use TypeScript.
- [x] Use React.
- [ ] ~~Use Redux for managing global states.~~
  > Was implemented, but not used
- [ ] ~~Use Redux Thunks or Redux Saga for managing asynchronous side effects.~~
  > Was implemented, but not used
- [x] Use Next.js or Vite.
  > Used vite
- [x] Use Material UI 5 for styling the application.
- [x] Create reusable components.
- [x] The code is well-organized and documented.
  > Could be improved
  > Lots of unnecessary comments
  > Lots of code unused
- [x] The application layout is responsive. The choice of remaining tools is at your discretion.
  > Some components can be improved about responsivity

6 - Bonus

- [ ] Implement unit tests for the application (let us know how to run them, otherwise we won't be able to evaluate).
- [x] Implement your own back-end code. If you pick this option, write it using NodeJS JavaScript runtime (not Java, not PHP...). Although we also work with Python here, we are looking for JavaScript related skills in this test.
- [x] If you choose to implement your own back-end, we encourage you to use either PostgreSQL or MongoDB as a persistence layer.
  > Mongo
- [x] If you choose to use PostgreSQL, use Prisma ORM (or even try Drizzle, or Kysely) to interact with PostgreSQL.
- [x] If you choose to use MongoDB, use Mongoose ORM to interact with the database;
- [ ] Use Nest.js Framework for the back-end (we are moving some services to that tool).
- [x] Use Nx to manage the whole application as a monorepo (we use that tool a lot here).
- [ ] Add e2e tests with Cypress (use it to test a full user flow).
- [ ] If you were provided with a baseline code, identify any areas of bad code or suboptimal implementations and refactor them.
- [x] Deploy your application to a cloud provider and provide a link for the running app.
  > Heroku

**Evaluation Criteria**

- [ ] Anyone should be able to follow the instructions and run the application.
  > Could be add steps to run the database
- [ ] User stories were implemented according to the functional requirements.
- [x] Front-end code is successfully integrated with a back-end API (either a fake one, or one you built yourself).
- [ ] Ability to refactor existing code (if applicable) and write unit tests for the written code.
- [ ] Adherence to best practices in front-end development.
- [x] Problem-solving skills and ability to handle ambiguity.
- [ ] Code quality, readability, and maintainability.

## Ready to Begin the Challenges?

- [x] Fork this repository to your own Github account.
  > The purpose of the 'fork' is to track the time the developer takes to complete the project, documenting the process through commits, which will serve as proof of their knowledge in Git
- [ ] Create a new branch using your first name and last name. For example: `caroline-oliveira`.
- [x] After completing the challenge, create a pull request to this repository (https://github.com/dynamox-s-a/js-ts-full-stack-test), aimed at the main branch.
  > Test was implemented in another repository and after done, the code was moved to the fork and pushed in only one commit

**Pull request closed without merging**
