### PR TITLE
Handryos dos santos challenge

### PR DESCRIPTION
**Pull request by handryos**
Olá,

Estou entregando o projeto completo conforme solicitado, através deste pull request.

### CODE REVIEW

**Comment by handryos** [comment]
Acabei esquecendo de disponibilizar o link para acessar a aplicação em produção.

Segue o link: https://dynamox-test.netlify.app/routes/login

**Comment by juarez-sacenti-dyx** [comment]
Obrigado pela submissão, Handryos, em breve comentamos com a avaliação de seu teste.

**Comment by juarez-sacenti-dyx** [comment]
Olá Handryos, tive um atraso na sua avaliação, peço desculpas.
Olhei brevemente e já gostei do layout do site.
Devo enviar a avaliação neste fim de semana.

**Comment by juarez-sacenti-dyx** [comment]
1 - Authentication

1. [x] As a user, I want to log in using a fixed email and password so that I can access private routes.
1. [x] As a user, I want to be able to log out of the system so that I can prevent unauthorized access to my account.
1. [x] No private routes should be accessible without authentication.

> Clean layout. :+1:
> Has a registration screen, email validation and password confirmation. No strong password validation. :-1:
> No users' context segregation, all user can see all data. :-1:
> JWT for session control, Bcrypt for password hashing, CryptoJS for payload encryption. Really good! :+1:

2 - Machine Management

1. [x] As a user, I want to create a new machine with an arbitrary name and with a type selected from a list ["Pump", "Fan"] so that I can manage it later.

> Cancel button gives a nice touch in navegation.  :+1:
>  "Checks for existing machines based on machine name to avoid duplicates." It was not required and maybe it is not a scalable feature. However, good effort for implementing it! :+1:

1. [x] As a user, I want to change the attributes (name and type) of a machine after creating it so that I can keep the machine information updated.

> edition screen has a bad behavior when refreshing the page. :-1:

1. [x] As a user, I want to delete a machine when it is no longer in use so that it doesn't clutter the system.

> "Throws an error if the machine has any associated monitoring points." Nice touch :+1:
> Note: incremental id, jumps after deletion. Soft deletion?

3 - Monitoring Points and Sensors Management

1. [x] As a user, I want to create at least two monitoring points with arbitrary names for an existing machine, so that I can monitor the machine's performance.
1. [ ] As a user, I want to associate a sensor to an existing monitoring point so that I can monitor the machine's performance. The sensor should have a unique ID, and the sensor model name should be one of ["TcAg", "TcAs", "HF+"].

> the sensor does not have a unique id. It was expected endpoints for sensors management. :-1:

1. [x] As a user, I want the system to prevent me from setting up "TcAg" and "TcAs" sensors for machines of the type "Pump".

> The system permits to change the machine type to PUMP when the machine has tcA* sensors. :-1:

1. [x] As a user, I want to see all my monitoring points in a paginated list so that I can manage them. The list should display up to 5 monitoring points per page and should include the following information: "Machine Name", "Machine Type", "Monitoring Point Name", and "Sensor Model".
1. [x] As a user, I want to sort the monitoring points list by any of its columns in ascending or descending order, so that I can easily find the information I'm looking for.

> Has filter and hide column features :+1: 

4 - Ambiguity Handling

1. [x] Make reasonable assumptions and design the application accordingly for any ambiguities in the challenge.
1. [x] Document your assumptions in the README file.

> Good README  :+1:

5 - Technical requirements

1. [x] Use TypeScript.
1. [x] Use React.
1. [x] Use Redux for managing global states.
1. [x] Use Redux Thunks or Redux Saga for managing asynchronous side effects.
1. [x] Use Next.js or Vite.
1. [x] Use Material UI 5 for styling the application.
1. [x] Create reusable components.
1. [x] The code is well-organized and documented.
1. [x] The application layout is responsive.

> Table components do not react well in small screens. :-1:

The choice of remaining tools is at your discretion.

6 - Bonus

1. [ ] Implement unit tests for the application (let us know how to run them, otherwise we won't be able to evaluate).
1. [x] Implement your own back-end code. If you pick this option, write it using NodeJS JavaScript runtime (not Java, not PHP...). Although we also work with Python here, we are looking for JavaScript related skills in this test.
1. [x] If you choose to implement your own back-end, we encourage you to use either PostgreSQL or MongoDB as a persistence layer.
1. [x] If you choose to use PostgreSQL, use Prisma ORM (or even try Drizzle, or Kysely) to interact with PostgreSQL.
1. [ ] If you choose to use MongoDB, use Mongoose ORM to interact with the database;
1. [x] Use Nest.js Framework for the back-end (we are moving some services to that tool).
1. [ ] Use Nx to manage the whole application as a monorepo (we use that tool a lot here).
1. [x] Add e2e tests with Cypress (use it to test a full user flow).
1. [x] Deploy your application to a cloud provider and provide a link for the running app.

> Backend and frontend deployed in different services; :+1:
> Nice touch with theme drawer and monitor (home) :+1: 
> Listing monitoring points endpoint is not database efficient (join). :-1:

## Evaluation Criteria

The items listed above will have different weights in the evaluation process. Each one of them will be evaluated as "Not Implemented", "Implemented with Issues", "Implemented", or "Implemented with Excellence". Use your judgement to prioritize the requirements you will implement in the time you have available. 

In general we will be looking for the following:

1. [ ] Anyone should be able to follow the instructions and run the application.

> No instructions about postgresql setup nor environment variables (I expected a .env.example file). :-1: 
> Missing configuration steps - CORS, secrets, etc. :-1: 

1. [x] User stories were implemented according to the functional requirements.

> Except sensor management

1. [x] Front-end code is successfully integrated with a back-end API (either a fake one, or one you built yourself).
1. [ ] Ability to refactor existing code (if applicable) and write unit tests for the written code.

> only e2e tests were found.

1. [x] Adherence to best practices in front-end development.
1. [x] Problem-solving skills and ability to handle ambiguity.
1. [x] Code quality, readability, and maintainability.

> The code is easy to read. :+1: 
> I expected more and smaller commits. :-1: 

Please wait our contact.

**Pull request closed without merging**
